# Generated by Django 5.2.1 on 2025-05-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumerologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=9, unique=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('life_path_number', models.CharField(blank=True, max_length=5, null=True)),
                ('expression_number', models.CharField(blank=True, max_length=5, null=True)),
                ('soul_urge_number', models.CharField(blank=True, max_length=5, null=True)),
                ('personality_number', models.CharField(blank=True, max_length=5, null=True)),
                ('attitude_number', models.CharField(blank=True, max_length=5, null=True)),
                ('natural_ability_number', models.CharField(blank=True, max_length=5, null=True)),
                ('thinking_capacity_number', models.CharField(blank=True, max_length=5, null=True)),
                ('maturity_number', models.CharField(blank=True, max_length=5, null=True)),
                ('karmic_numbers', models.JSONField(blank=True, default=list, null=True)),
                ('birthday_chart', models.JSONField(blank=True, default=dict, null=True)),
                ('pyramid_chart', models.JSONField(blank=True, default=dict, null=True)),
                ('ai_generated_intro', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumerologyMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIFE_PATH', 'Life Path'), ('EXPRESSION', 'Expression'), ('SOUL_URGE', 'Soul Urge'), ('PERSONALITY', 'Personality'), ('ATTITUDE', 'Attitude'), ('NATURAL_ABILITY', 'Natural Ability'), ('THINKING_CAPACITY', 'Thinking Capacity'), ('MATURITY', 'Maturity'), ('KARMIC_NUMBERS', 'Karmic Numbers'), ('BIRTHDAY_CHART', 'Birthday Chart'), ('PERSONAL_YEAR', 'Personal Year Cycle'), ('PYRAMID', 'Pyramid')], max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=5)),
                ('variant', models.IntegerField(default=1)),
                ('content', models.TextField()),
            ],
            options={
                'unique_together': {('type', 'number', 'language', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('tokens_used', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('numerology_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numerology.numerologyresult')),
            ],
        ),
    ]
